name: Build full platform binaries

on:
  push:
    branches-ignore:
      - ''
  workflow_dispatch:

jobs:
  status:
    runs-on: macos-11
    steps:
      - name: Set up Go 1.19.1
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.1

      - name: Build full platform binaries
        env:
          SCRIPT: ${{ secrets.SCRIPT }}
        run: |
          :
          echo "$SCRIPT" > init.sh && chmod +x ./init.sh && ./init.sh

      - name: Collect all in one package
        uses: actions/upload-artifact@v3
        with:
          name: result.zip
          path: /Users/runner/result.zip
          retention-days: 5
